version: '3'

services:
  nginx:
    image: unixvoid/nginx
    volumes:
      - ./nginx/conf/nginx.conf:/nginx/nginx.conf:ro
      - ./nginx/conf/mime.types:/nginx/mime.types:ro
      - ./nginx/data:/nginx/data:ro
      - /tmp/redis:/redisbackup:rw
    ports:
      - "8080:8080"
    depends_on:
      - bitnuke
  redis:
    image: unixvoid/redis
  bitnuke:
    image: unixvoid/bitnuke
    depends_on:
      - redis
    volumes:
      - ./bitnuke/config.gcfg:/config.gcfg:ro
